#!/bin/bash
# Builder script, see README. Run from ..!
# This is not run by CI. Run manually and commit the resulting files.

for goal in */; do
    goal=${goal%*/} # Remove trailing slash
    IFS='/' read -r -a parts <<< "$goal"

    version="${parts[0]}"

    if [[ "builder" == "$version" ]]
    then
        continue
    fi
    echo "# THIS IS AUTO-GENERATED by builder/build.sh. DO NOT EDIT." > "$version/Dockerfile"

    echo "FROM opensearchproject/opensearch:$version" >> "$version/Dockerfile"

    # Read base Dockefile, first three lines are skipped.
    tail -n +4 builder/Dockerfile >> "$version/Dockerfile"

    cp "README.md" "$version/"
    echo "$version/"

done
