# Dockerfile for all builds. The FROM part is switched out. Built by build.sh. See README. First three lines are stripped.
FROM opensearchproject/opensearch
##################################################################################

USER root

RUN yum install -y util-linux

USER opensearch
