#!/bin/bash
# Builder script, see README. Run from ..!
# This is not run by CI. Run manually and commit the resulting files.

for goal in */*/*/; do
    goal=${goal%*/} # Remove trailing slash
    IFS='/' read -r -a parts <<< "$goal"

    version="${parts[0]}"
    base="${parts[1]}"
    variant="${parts[2]}"

    if [[ "builder" == "$version" ]]
    then
        continue
    fi
    echo "# THIS IS AUTO-GENERATED by builder/build.sh. DO NOT EDIT." > "$version/$base/$variant/Dockerfile"
    echo "FROM php:$version-$variant-$base" >> "$version/$base/$variant/Dockerfile"
    # Read base Dockefile, first three lines are skipped.
    tail -n +4 builder/Dockerfile >> "$version/$base/$variant/Dockerfile"
done