include base.makefile

# Add additional targets here or extend(::)/override(:) some, e.g.:

# New target
#install-my-project: ## description for install-my-project
#	@echo project installation steps

# Extend: Further init directories
#init-directories::
#	@[ -d ~/dir ] || mkdir ~/dir

# Override: New Node.js installation steps
#install-nodejs:
#	@echo install it some other way
